# Generated by Django 2.1.5 on 2019-02-12 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='Name', default='', max_length=100)),
                ('connection_method', models.CharField(blank=True, db_column='Connection Method', default='', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='Product Name', default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, db_column='Date')),
                ('quantity', models.PositiveIntegerField(db_column='Quantity', default=0)),
                ('unit_cost', models.DecimalField(db_column='Unit Cost', decimal_places=2, default=0, max_digits=10)),
                ('product_id', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, related_name='products_purchases', to='home.Products')),
            ],
        ),
        migrations.CreateModel(
            name='Skus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, db_column='Sku', default='', max_length=255)),
                ('product_id', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, related_name='products_skus', to='home.Products')),
            ],
        ),
        migrations.CreateModel(
            name='Store_fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, db_column='Date')),
                ('type', models.CharField(blank=True, db_column='Type', default='', max_length=100)),
                ('description', models.CharField(blank=True, db_column='Description', default='', max_length=100)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='Name', default='', max_length=100)),
                ('api_key', models.CharField(blank=True, db_column='Api Key', default='', max_length=255)),
                ('user_key', models.CharField(blank=True, db_column='User Key', default='', max_length=255)),
                ('store_key', models.CharField(blank=True, db_column='Store Key', default='', max_length=255)),
                ('marketplace_id', models.ForeignKey(db_column='MarketplaceID', on_delete=django.db.models.deletion.CASCADE, related_name='marketplaces_stores', to='home.Marketplaces')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, db_column='Date')),
                ('type', models.CharField(blank=True, db_column='Type', default='', max_length=100)),
                ('description', models.CharField(blank=True, db_column='Description', default='', max_length=100)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, db_column='Type', default='', max_length=100)),
                ('date', models.DateField(auto_now_add=True, db_column='Date')),
                ('sku_sku', models.CharField(blank=True, db_column='Sku_Sku', default='', max_length=255)),
                ('quantity', models.PositiveIntegerField(db_column='Quantity', default=0)),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, default=0, max_digits=10)),
                ('sku_store_id', models.ForeignKey(db_column='Sku-StoreID', on_delete=django.db.models.deletion.CASCADE, related_name='skus_transactions', to='home.Skus')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, db_column='Email', default='', max_length=100)),
                ('password', models.CharField(blank=True, db_column='Password', default='', max_length=255)),
                ('tier', models.CharField(blank=True, db_column='Account Tier', default='', max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='transaction_fees',
            name='transaction_id',
            field=models.ForeignKey(db_column='TransactionID', on_delete=django.db.models.deletion.CASCADE, related_name='transactions_transaction_fees', to='home.Transactions'),
        ),
        migrations.AddField(
            model_name='stores',
            name='user_id',
            field=models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='users_stores', to='home.Users'),
        ),
        migrations.AddField(
            model_name='store_fees',
            name='store_id',
            field=models.ForeignKey(db_column='StoreID', on_delete=django.db.models.deletion.CASCADE, related_name='stores_store_fees', to='home.Stores'),
        ),
        migrations.AddField(
            model_name='skus',
            name='store_id',
            field=models.ForeignKey(db_column='StoreID', on_delete=django.db.models.deletion.CASCADE, related_name='stores_skus', to='home.Stores'),
        ),
        migrations.AddField(
            model_name='products',
            name='user_id',
            field=models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='users_products', to='home.Users'),
        ),
    ]
